name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Setups Node
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@bitabs'

      - uses: nrwl/nx-set-shas@v2
      - run: npm ci

      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: npx nx affected --target=build --parallel=3
