name: CI
on:
  push:
    branches:
      - main
      - integrate-nx
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@bitabs'
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - run: npm ci

      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: npx nx affected --target=build --parallel=3
